### ISSUE TITLE
Top level node aggregates an error result

### ISSUE THREAD

**Issue by Ryan-Gao** [aritzfb/TreeCircle#1]
![snipaste_20181102_164114](https://user-images.githubusercontent.com/28983335/47903337-861cff80-debe-11e8-9f3f-d0ea33f4d576.png)

**Comment by aritzfb** [comment]
Thanks Ryan-Gao for your report. May you send to me the pbi file?
Regards,

**Comment by aritzfb** [comment]
![captura de pantalla de 2018-11-06 23-40-34](https://user-images.githubusercontent.com/44166100/48098613-9b2ac300-e21d-11e8-9d17-4e59894d3e1a.png)

**Comment by aritzfb** [comment]
Solved in last commit

**Comment by aritzfb** [comment]
Close the issue.
Thanks for your help

**Comment by aritzfb** [comment]
Cleaner:
![captura de pantalla de 2018-11-06 23-44-41](https://user-images.githubusercontent.com/44166100/48098800-007eb400-e21e-11e8-8f85-6d416f0c2eb7.png)
