### ISSUE TITLE
Showing numbers as Percentages

### ISSUE THREAD

**Issue by akhilhangout** [aritzfb/TreeCircle#11]
Would be great to have the ability to display the tree label number as percentages.   After using the latest version from #10 , I observed that the pie at the start of the link (and the tooltip) display the percentage correctly,   
If the amount is data is high,  or if we are looking at many nodes it is very easy to understand if we can just display the percentages instead of numbers. 
This is useful when there is no specific target value, but just data drill down to explore different paths.

**Comment by aritzfb** [comment]
added option value as percentage (over parent)
