### ISSUE TITLE
Tree not showing value numbers on parent totalvalue = 0

### ISSUE THREAD

**Issue by CN91** [aritzfb/TreeCircle#12]
When I try to use the tree, and select a values field it won't show any values. After trying to reproduce with the example report, I figured out it doesn't show any values if a complete branch returns 0.

**To Reproduce**
Create a tree, where one of the branches and all of it's children are zero. 
Or just create a parent with value 0

**Expected behavior**
It should show the tree with values, and this branch should still show and show value 0.

** What it does now **
Doesn't show a single value (also not those that are above 0).

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  : Windows 10
 - Browser [e.g. chrome, safari] none -> in  PowerBi (latest version)

**Comment by CN91** [comment]
I've done some debugging myself and found some solutions:

At this place : https://github.com/aritzfb/TreeCircle/blob/22a09339a4b2546b5334a4d162075b2c99e6e97c/node_modules/funciones-arbol.js#L60

you should typecheck the value since 0 is also checked as 'doesn't exist'. 
So it should become if(rowValue != null) 

And at the second place: https://github.com/aritzfb/TreeCircle/blob/22a09339a4b2546b5334a4d162075b2c99e6e97c/node_modules/funciones-arbol.js#L379 

I've checked for rows containing "" , if they do I don't push them. However maybe that one is more inside our datamodel. Not sure, however when using both two fixes my tree shows including 0's

**Comment by aritzfb** [comment]
Hello,

Thanks for try the visual and thanks for report the issue, and thanks for the sollution!!! 
If you want, be free to open a branch inside git and apply the changes by yourself. If you want to use the modifications, remember to change the app GUID before you generate the pbiviz file because if you don't do it, you won't see any change because PBI uses the visual stored in the marketplace.
I will try to add your fixes this week to the code. But, it will take more time to deploy the sollution for Marketplace.

**Comment by CN91** [comment]
Hi, 

I relooked at the code with another colleague, and we only need the if (rowValue) to be changed, you could make the change the else statement. I will fork your branch and make a PR .

The check for "" can be left out.

**Comment by aritzfb** [comment]
Fantastic! I've merged your PR to the master branch. Can I close the issue or do you want to modify anything else?

**Comment by CN91** [comment]
You can close this issue :) maybe it also solved the other issue with not displaying the first level.
