### ISSUE TITLE
not compatible with Power BI version March

### ISSUE THREAD

**Issue by sophiafly123** [aritzfb/TreeCircle#14]
When using Power BI desktop (version in march), the chart is lack of interaction with other charts. i.e. if I click on one segment of a donut chart in the same page or one line of a table chart, the value and shape of pie chart tree do not change.

**Comment by aritzfb** [comment]
Hello,
I will work on it. Meanwhile, you can use the visual and disable the interacions of other visuals to Pie Charts Tree as workarround.
Regards

**Comment by aritzfb** [comment]
Solved in review eb6162625ee11a51839eea0a255a845c72c33f23
