### ISSUE TITLE
thousands separator not displayed

### ISSUE THREAD

**Issue by bojaboja** [aritzfb/TreeCircle#19]
Hi,

I like your visual, i use it very often. Could you please add an ability to display thousands separator? I tried with FORMAT function and some other ways, but it only shows decimal separator. 

Thank you

Boja

**Comment by aritzfb** [comment]
Hello, i will add decimal and thousand separators as options

**Comment by aritzfb** [comment]
solved in 863ed5b7030d5ea47cfd1c957d0bc6d0ea166283
