### ISSUE TITLE
Values and Units Altered

### ISSUE THREAD

**Issue by jtares** [aritzfb/TreeCircle#20]
![values](https://user-images.githubusercontent.com/53495935/62169484-33516680-b2dd-11e9-97db-68b6f0ada9af.jpg)
![graphic](https://user-images.githubusercontent.com/53495935/62169499-3cdace80-b2dd-11e9-8cec-fd7f3b60f6d7.jpg)

In the graphic the autoscale has altered the true values and units (ie 51,815,795,577 to 0.05 B and 3,420,222,029 to 3.42 kM). How can I fix these to the correct values and units (ie 51,815,795,577 to 51.82 B and 3,420,222,029 to 3.42 B).

**Comment by aritzfb** [comment]
You can set the option "Auto Scale Values" to off. It's under "Tree Labels" section. I will change the literals B (billions) and kM but you will see 0.05 kB. The other amount will look as you want.

**Comment by aritzfb** [comment]
Solved in 18fc6efeb04421fc2c507acc674007b118c2968c
