### ISSUE TITLE
Incorrect values when child node value is 0

### ISSUE THREAD

**Issue by lflugo22** [aritzfb/TreeCircle#26]
**Describe the bug**
When a child node has a value of 0, the parent node displays an incorrect value. In the case below, it seems to double the value of the first non-zero node value. This behavior also occurs in the latest build on Github.

![image](https://user-images.githubusercontent.com/10080932/70280592-c405ea80-1786-11ea-98e2-0e0b9624d02b.png)

By the way, I really like this visual, and it is almost perfect for the family of contracts reports I am building.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 78.0.3904.108 (Official Build) (64-bit)

**Comment by lflugo22** [comment]
I was able to fix locally by changing line 71 of funciones-arbol.js as follows:
        rowValue == 0 ? retorno.hasValue = true : retorno.hasValue = false;

![image](https://user-images.githubusercontent.com/10080932/70567803-a230ad00-1b64-11ea-80b6-a978c82766b5.png)

![image](https://user-images.githubusercontent.com/10080932/70567928-e02dd100-1b64-11ea-9ba6-293fb52a3575.png)

**Comment by aritzfb** [comment]
Nice!

**Comment by lflugo22** [comment]
Wondering if it's just easier, and cleaner, to just set retorno.hasValue to "true" in either case since you are setting the value to zero.

**Comment by aritzfb** [comment]
Solved by Luis Lugo
