### ISSUE TITLE
Not all categories included

### ISSUE THREAD

**Issue by Avtandyl** [aritzfb/TreeCircle#3]
Hi. I use Your visual for visualising relations between customers in hierarchical way. I have more than 200 relation between different customers and noticed that at some point visual cut off relations andd include not all that i have in datasource.
Could you clarify why i have such situation? Maybe there is some limit on number of categories? And also want to ask could you give functionality that values doesnt sum? I dont need this in my task. I need to show share of one person in public enterpice.Thank You

**Comment by aritzfb** [comment]
Hello,
Thanks for try the visual. I think the issue could be related with the number of rows that returns the model, but i'm not sure. May you send me a PowerBI file that shows the problem? It's not neccesary you use your data (if it's sensitive), you can send me any data model.
Another cause would be the api version that uses the visual. The version 1.0.2 it's developed over 1.10 PBI api version. I'm working for migrate the visual to 2.2 api version. You can try it downloading the lastest version here, in git. If you don't know how to do it, tell to me and i send to you the pbiviz file with 2.2 api version.
Thanks for the report
I am looking forward to your response
Regards

**Comment by aritzfb** [comment]
Hello again,
Solved total values over datasets with less than 8 categories and less than 500 rows in the commit https://github.com/aritzfb/TreeCircle/commit/778cab78da44f29a00107240955bef897bb9bc03
It will be realeased into 1.0.3 version
If your problem persists with this new version, please re-open the issue.
Regards,
